{
  "props": [],
  "components": {
    "UIload": {
      "type": "script\\MacroScript",
      "x": 240,
      "y": 48,
      "props": {}
    },
    "fileChooser": {
      "type": "script\\FileChooserScript",
      "x": 32,
      "y": 32,
      "props": {
        "filterName": "exe-файл",
        "filterExtensions": "*.exe",
        "filterAny": "0",
        "inputNode": "",
        "actionNode": ""
      }
    }
  }
}